@echo off
del /s /q ".\*.vcxproj.user"
del /s /q ".\*.unsuccessfulbuild"
del /s /q ".\*.lastbuildstate"
del /s /q ".\*.log"
del /s /q ".\*.pdb"
del /s /q ".\*.idb"
del /s /q ".\*.tlog"
del /s /q ".\*.sdf"
del /s /q ".\*.ipch"
del /s /q ".\*.obj"
del /s /q ".\*.aps"
del /s /q ".\*.pch"
del /s /q ".\*.intermediate.manifest"
pause